//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Domain.Entities
{
    using Microsoft.EntityFrameworkCore;

    public partial class ShopEntities : DbContext
    {
        public ShopEntities()            
        {
            Database.EnsureCreated();
        }
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(@"Data Source=WIN-CPD07VPF2LM\SQLEXPRESS;Initial Catalog = Shop; Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
        }

        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryConnection> CategoryConnection { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<DeliveryProductConnection> DeliveryProductConnection { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderProductConnection> OrderProductConnection { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductImage> ProductImage { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }       
    }
}
