//------------------------------------------------------------------------------
// <auto-generated>
namespace Shop.Domain.Entities
{
    using Shop.Domain.Entities.Base;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Sellers : EntityBase
    {
        public Sellers()
        {
            this.Product = new HashSet<Product>();
        }       
        public string Name { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }  
        public virtual ICollection<Product> Product { get; set; }
    }
}
